import type { Lang } from "@/lib/i18n";
import type { LegalBlock } from "@/lib/content/legal";

/**
 * THE ONE-WAY DOOR: hand-authored FAQ answers → the markdown the Hub will hold.
 *
 * The FAQ is authored in this repo as `LegalBlock[]` (lib/content/faq.ts) and
 * rendered by the same component the legal pages use. It is moving into the
 * Hub, where an answer is one markdown column per language. This is the
 * conversion, and it is used three times over:
 *
 *   docs/faq-seed.sql        the rows Cynthia runs once, generated from here
 *   lib/fixtures.ts          the preview FAQ, so the preview exercises the Hub
 *                            path against the real answers
 *   scripts/check-faq.mjs    the gate that proves the two say the same thing
 *
 * ONE CONVERTER FOR ALL THREE, because a seed generated by one function and
 * checked by another is a seed nobody checked.
 *
 * THE RULE IT MUST NOT BREAK: the FAQ is authoritative and much of it is terms
 * — cancellation charges, store-credit expiry, layaway schedules. Not one word
 * may change on the way through. `scripts/check-faq.mjs` renders both the
 * blocks and the markdown to plain text and asserts they are identical, which
 * is the only assertion that actually covers that promise.
 *
 * TYPE-ONLY IMPORTS, DELIBERATELY. Node runs this file directly (type stripping,
 * no bundler) for the generator and the gate, and a runtime `@/` import would
 * not resolve there.
 */

/**
 * ESCAPING, KEPT AS SMALL AS IT CAN BE.
 *
 * The markdown this produces is what an owner will EDIT in the Hub, so an
 * over-eager escaper is not a harmless safety margin — a rule that escaped
 * every `.` and `-` turned "Yes. We inspect…" into "Yes\. We inspect…" and
 * "Live-Selling" into "Live\-Selling", which is unreadable in an editor and
 * invites someone to "fix" it by deleting backslashes that were load-bearing.
 *
 * So: the six characters that mean something ANYWHERE in a line are escaped
 * anywhere, and the ones that only mean something at the START of a line are
 * escaped only there. That is the whole rule.
 *
 * NOTHING IN THE FAQ NEEDS EITHER TODAY — all 322 strings are clean, and the
 * generated seed contains no backslash but the hard breaks. It is here so the
 * converter is TOTAL rather than correct-by-luck: an owner writing "the 30% *
 * asterisk note" next month gets an asterisk on the page, not emphasis, and
 * scripts/check-faq.mjs stays green instead of reporting a mystery.
 */
const INLINE = /([\\`*_[\]])/g;
/** `#` `-` `+` `>` and `1.` / `1)` are list, heading and quote markers. */
const LINE_START = /^(\s*)([#\-+>]|\d+[.)])/;

/** Escapes what is significant anywhere in a line. */
function escapeInline(text: string): string {
  return text.replace(INLINE, "\\$1");
}

/** Additionally escapes what is significant only where a line begins. */
function escapeLine(text: string): string {
  return escapeInline(text).replace(LINE_START, (_, space: string, marker: string) => `${space}\\${marker}`);
}

/**
 * One answer, in one language, as markdown.
 *
 *   p      a paragraph
 *   h      `###` — h3, because an answer already sits under the section's h2
 *          and the question's summary. No answer uses one today; LegalBlock is
 *          shared with the legal pages and this must not be the switch that
 *          silently drops a block someone adds there.
 *   list   `- ` bullets, one block
 *   lines  one paragraph with HARD BREAKS, because the breaks carry meaning:
 *          these are contact lines, not wrapped prose
 *   rich   prose with `[text](href)` inline. Runs are concatenated with NO
 *          separator — each already carries its own spacing, which is why
 *          answerText joins them the same way.
 */
export function blocksToMarkdown(blocks: LegalBlock[], lang: Lang): string {
  return blocks
    .map((b) => {
      switch (b.kind) {
        case "p":
          return escapeLine(b.text[lang]);
        case "h":
          // The text follows "### ", so it is no longer at the start of a line.
          return `### ${escapeInline(b.text[lang])}`;
        case "list":
          return b.items[lang].map((item) => `- ${escapeInline(item)}`).join("\n");
        case "lines":
          // Trailing backslash rather than two trailing spaces: both are hard
          // breaks in markdown, but only one of them survives a database
          // column, an editor that trims lines, and a reviewer's eye.
          return b.lines[lang].map(escapeLine).join("\\\n");
        case "rich":
          // Only the FIRST run begins the line; the rest are mid-sentence.
          return b.runs[lang]
            .map((run, i) => {
              const esc = i === 0 && !run.href ? escapeLine : escapeInline;
              return run.href ? `[${escapeInline(run.t)}](${run.href})` : esc(run.t);
            })
            .join("");
      }
    })
    .join("\n\n");
}

/** A section heading → its stable slug. The Hub's rows are keyed on this. */
export function sectionSlug(headingEn: string): string {
  return headingEn
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
