// Generated by `npm run db:types` against the shared Hub project. Until then this is intentionally loose;
// the website's own row shapes live in lib/types.ts and queries pin their result types explicitly.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
